name: Build/release

on:
  push:
    tags: 
    - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 17 
      - run: npm install
      - run: npm run app:dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          asset_paths: '["./dist/jlab-electron-app-*.AppImage", "./dist/jlab-electron-app-Setup-*.exe", "./dist/jlab-electron-app_*.snap", "./dist/jlab-electron-app-*.dmg"]'

